comment: false
coverage:
  range: 50..100
  round: down
  precision: 2
  status:
    patch: false
    default_rules:
      flag_coverage_not_uploaded_behavior: exclude
    project:
      default:
        target: 75
        if_ci_failed: error
      AWS_Pricing:
        target: 75
        flags:
        - aws_pricing
      Aqua:
        target: 75
        flags:
        - aqua
      BIND_9:
        target: 75
        flags:
        - bind9
      Cloudsmith:
        target: 75
        flags:
        - cloudsmith
      Cyral:
        target: 75
        flags:
        - cyral
      Eventstore:
        target: 75
        flags:
        - eventstore
      Filebeat:
        target: 75
        flags:
        - filebeat
      Fluent_Bit:
        target: 75
        flags:
        - fluentbit
      Gatekeeper:
        target: 75
        flags:
        - gatekeeper
      Gitea:
        target: 75
        flags:
        - gitea
      Gnatsd:
        target: 75
        flags:
        - gnatsd
      Gnatsd_Streaming:
        target: 75
        flags:
        - gnatsd_streaming
      gRPC_Check:
        target: 75
        flags:
        - grpc_check
      JFrog_Platform:
        target: 75
        flags:
        - jfrog_platform
      Kernelcare:
        target: 75
        flags:
        - kernelcare
      Lighthouse:
        target: 75
        flags:
        - lighthouse
      Logstash:
        target: 75
        flags:
        - logstash
      NS1:
        target: 75
        flags:
        - ns1
      Neo4j:
        target: 75
        flags:
        - neo4j
      Netnology_SD-WAN:
        target: 75
        flags:
        - nn_sdwan
      Neutrona:
        target: 60
        flags:
        - neutrona
      Nextcloud:
        target: 75
        flags:
        - nextcloud
      OctoPrint:
        target: 75
        flags:
        - octoprint
      PHP_APCu:
        target: 75
        flags:
        - php_apcu
      PHP_OPcache:
        target: 75
        flags:
        - php_opcache
      Ping:
        target: 75
        flags:
        - ping
      Portworx:
        target: 75
        flags:
        - portworx
      Puma:
        target: 75
        flags:
        - puma
      PureFA:
        target: 75
        flags:
        - purefa
      PureFB:
        target: 75
        flags:
        - purefb
      Reboot_Required:
        target: 75
        flags:
        - reboot_required
      Redis_Enterprise:
        target: 75
        flags:
        - redisenterprise
      Redis_Sentinel:
        target: 75
        flags:
        - redis_sentinel
      Redpanda:
        target: 75
        flags:
        - redpanda
      Riak_MDC_Replication:
        target: 75
        flags:
        - riak_repl
      Sendmail:
        target: 75
        flags:
        - sendmail
      Snmpwalk:
        target: 75
        flags:
        - snmpwalk
      Sortdb:
        target: 75
        flags:
        - sortdb
      Stardog:
        target: 70
        flags:
        - stardog
      Storm:
        target: 75
        flags:
        - storm
      Syncthing:
        target: 75
        flags:
        - syncthing
      TiDB:
        target: 75
        flags:
        - tidb
      Traefik:
        target: 75
        flags:
        - traefik
      Trino:
        target: 75
        flags:
        - trino
      UPSC:
        target: 75
        flags:
        - upsc
      Unbound:
        target: 75
        flags:
        - unbound
      Unifi_Console:
        target: 75
        flags:
        - unifi_console
      Vespa:
        target: 75
        flags:
        - vespa
      Zabbix:
        target: 50
        flags:
        - zabbix
      fluxcd:
        target: 75
        flags:
        - fluxcd
      exim:
        target: 75
        flags:
        - exim
      cfssl:
        target: 75
        flags:
        - cfssl
      nvml:
        target: 75
        flags:
        - nvml
      open_policy_agent:
        target: 75
        flags:
        - open_policy_agent
      pihole:
        target: 75
        flags:
        - pihole
      PureFA:
        target: 75
        flags:
        - purefa
      PureFB:
        target: 75
        flags:
        - purefb
      speedtest:
        target: 75
        flags:
        - speedtest
flags:
  aqua:
    carryforward: true
    paths:
    - aqua/datadog_checks/aqua
    - aqua/tests
  aws_pricing:
    carryforward: true
    paths:
    - aws_pricing/datadog_checks/aws_pricing
    - aws_pricing/tests
  bind9:
    carryforward: true
    paths:
    - bind9/datadog_checks/bind9
    - bind9/tests
  cfssl:
    carryforward: true
    paths:
    - cfssl/datadog_checks/cfssl
    - cfssl/tests
  cloudsmith:
    carryforward: true
    paths:
    - cloudsmith/datadog_checks/cloudsmith
    - cloudsmith/tests
  cyral:
    carryforward: true
    paths:
    - cyral/datadog_checks/cyral
    - cyral/tests
  eventstore:
    carryforward: true
    paths:
    - eventstore/datadog_checks/eventstore
    - eventstore/tests
  exim:
    carryforward: true
    paths:
    - exim/datadog_checks/exim
    - exim/tests
  filebeat:
    carryforward: true
    paths:
    - filebeat/datadog_checks/filebeat
    - filebeat/tests
  fluentbit:
    carryforward: true
    paths:
    - fluentbit/datadog_checks/fluentbit
    - fluentbit/tests
  fluxcd:
    carryforward: true
    paths:
    - fluxcd/datadog_checks/fluxcd
    - fluxcd/tests
  gatekeeper:
    carryforward: true
    paths:
    - gatekeeper/datadog_checks/gatekeeper
    - gatekeeper/tests
  gitea:
    carryforward: true
    paths:
    - gitea/datadog_checks/gitea
    - gitea/tests
  gnatsd:
    carryforward: true
    paths:
    - gnatsd/datadog_checks/gnatsd
    - gnatsd/tests
  gnatsd_streaming:
    carryforward: true
    paths:
    - gnatsd_streaming/datadog_checks/gnatsd_streaming
    - gnatsd_streaming/tests
  grpc_check:
    carryforward: true
    paths:
    - grpc_check/datadog_checks/grpc_check
    - grpc_check/tests
  jfrog_platform:
    carryforward: true
    paths:
    - jfrog_platform/datadog_checks/jfrog_platform
    - jfrog_platform/tests
  kernelcare:
    carryforward: true
    paths:
    - kernelcare/datadog_checks/kernelcare
    - kernelcare/tests
  lighthouse:
    carryforward: true
    paths:
    - lighthouse/datadog_checks/lighthouse
    - lighthouse/tests
  logstash:
    carryforward: true
    paths:
    - logstash/datadog_checks/logstash
    - logstash/tests
  neo4j:
    carryforward: true
    paths:
    - neo4j/datadog_checks/neo4j
    - neo4j/tests
  neutrona:
    carryforward: true
    paths:
    - neutrona/datadog_checks/neutrona
    - neutrona/tests
  nextcloud:
    carryforward: true
    paths:
    - nextcloud/datadog_checks/nextcloud
    - nextcloud/tests
  nn_sdwan:
    carryforward: true
    paths:
    - nn_sdwan/datadog_checks/nn_sdwan
    - nn_sdwan/tests
  ns1:
    carryforward: true
    paths:
    - ns1/datadog_checks/ns1
    - ns1/tests
  nvml:
    carryforward: true
    paths:
    - nvml/datadog_checks/nvml
    - nvml/tests
  octoprint:
    carryforward: true
    paths:
    - octoprint/datadog_checks/octoprint
    - octoprint/tests
  open_policy_agent:
    carryforward: true
    paths:
    - open_policy_agent/datadog_checks/open_policy_agent
    - open_policy_agent/tests
  php_apcu:
    carryforward: true
    paths:
    - php_apcu/datadog_checks/php_apcu
    - php_apcu/tests
  php_opcache:
    carryforward: true
    paths:
    - php_opcache/datadog_checks/php_opcache
    - php_opcache/tests
  pihole:
    carryforward: true
    paths:
    - pihole/datadog_checks/pihole
    - pihole/tests
  ping:
    carryforward: true
    paths:
    - ping/datadog_checks/ping
    - ping/tests
  portworx:
    carryforward: true
    paths:
    - portworx/datadog_checks/portworx
    - portworx/tests
  puma:
    carryforward: true
    paths:
    - puma/datadog_checks/puma
    - puma/tests
  purefa:
    carryforward: true
    paths:
    - purefa/datadog_checks/purefa
    - purefa/tests
  purefb:
    carryforward: true
    paths:
    - purefb/datadog_checks/purefb
    - purefb/tests
  reboot_required:
    carryforward: true
    paths:
    - reboot_required/datadog_checks/reboot_required
    - reboot_required/tests
  redis_sentinel:
    carryforward: true
    paths:
    - redis_sentinel/datadog_checks/redis_sentinel
    - redis_sentinel/tests
  redisenterprise:
    carryforward: true
    paths:
    - redisenterprise/datadog_checks/redisenterprise
    - redisenterprise/tests
  redpanda:
    carryforward: true
    paths:
    - redpanda/datadog_checks/redpanda
    - redpanda/tests
  riak_repl:
    carryforward: true
    paths:
    - riak_repl/datadog_checks/riak_repl
    - riak_repl/tests
  sendmail:
    carryforward: true
    paths:
    - sendmail/datadog_checks/sendmail
    - sendmail/tests
  snmpwalk:
    carryforward: true
    paths:
    - snmpwalk/datadog_checks/snmpwalk
    - snmpwalk/tests
  sortdb:
    carryforward: true
    paths:
    - sortdb/datadog_checks/sortdb
    - sortdb/tests
  speedtest:
    carryforward: true
    paths:
    - speedtest/datadog_checks/speedtest
    - speedtest/tests
  stardog:
    carryforward: true
    paths:
    - stardog/datadog_checks/stardog
    - stardog/tests
  storm:
    carryforward: true
    paths:
    - storm/datadog_checks/storm
    - storm/tests
  syncthing:
    carryforward: true
    paths:
    - syncthing/datadog_checks/syncthing
    - syncthing/tests
  tidb:
    carryforward: true
    paths:
    - tidb/datadog_checks/tidb
    - tidb/tests
  traefik:
    carryforward: true
    paths:
    - traefik/datadog_checks/traefik
    - traefik/tests
  trino:
    carryforward: true
    paths:
    - trino/datadog_checks/trino
    - trino/tests
  unbound:
    carryforward: true
    paths:
    - unbound/datadog_checks/unbound
    - unbound/tests
  unifi_console:
    carryforward: true
    paths:
    - unifi_console/datadog_checks/unifi_console
    - unifi_console/tests
  upsc:
    carryforward: true
    paths:
    - upsc/datadog_checks/upsc
    - upsc/tests
  vespa:
    carryforward: true
    paths:
    - vespa/datadog_checks/vespa
    - vespa/tests
  zabbix:
    carryforward: true
    paths:
    - zabbix/datadog_checks/zabbix
    - zabbix/tests
