name: validations

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

env:
  CHANGED: ${{ github.event_name == 'pull_request' && 'changed' || '' }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Upgrade Python packaging tools
      run: pip install --disable-pip-version-check --upgrade pip setuptools wheel

    - name: Install ddev
      run: pip install "datadog-checks-dev[cli]"

    - name: Configure ddev
      run: |
        ddev config set repos.extras .
        ddev config set repo extras
        ddev config set orgs.ci.dd_url "https://app.datadoghq.com"
        ddev config set org ci
        ddev ci setup

    - name: Run CI validation
      run: |
        ddev validate ci

    - name: Run codeowners validation
      run: |
        ddev validate codeowners

    - name: Run configuration validation
      run: |
        ddev validate config $CHANGED

    - name: Run dashboard validation
      run: |
        ddev validate dashboards $CHANGED

#    - name: Run HTTP wrapper validation
#      run: |
#        ddev validate http $CHANGED

    - name: Run imports validation
      run: |
        ddev validate imports $CHANGED
        
    - name: Run JMX metrics validation
      run: |
        ddev validate jmx-metrics $CHANGED

    - name: Run manifest validation
      run: |
        ddev validate manifest $CHANGED
        
    - name: Run metadata validation
      run: |
        ddev validate metadata $CHANGED

    - name: Run models validation
      run: |
        ddev validate models $CHANGED
  
    - name: Run legacy signature validation
      run: |
        ddev validate legacy-signature $CHANGED

    - name: Run licenses validation
      run: |
        ddev validate licenses

    - name: Run readmes validation
      run: |
        ddev validate readmes $CHANGED

    - name: Run recommended monitors validation
      run: |
        ddev validate recommended-monitors $CHANGED

    - name: Run package validation
      run: |
        ddev validate package $CHANGED

    - name: Run saved views validation
      run: |
        ddev validate saved-views $CHANGED
        
    - name: Run service checks validation
      run: |
        ddev validate service-checks $CHANGED

    - name: Comment PR on failure
      if: failure()
      continue-on-error: true
      uses: actions/github-script@0.3.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
          github.issues.createComment({ issue_number, owner, repo, body: "The `validations` job has failed; please review the `Files changed` tab for possible suggestions to resolve." });
